#!/usr/bin/env bash
# installs nginx on web-01
# creates an index.html file with hello world! text

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
