#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me redirects to another page

apt-get update
apt-get -y install nginx
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent"
sed -i "28i $redirect" /etc/nginx/sites-enabled/default
service nginx restart
service nginx reload
