#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me redirects to another page

apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
service nginx restart
service nginx reload
