#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me redirects to another page

sudo apt update
sudo apt -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
newinput="\\\trewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "28i $newinput" /etc/nginx/sites-available/default
sudo service nginx restart
