#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

sudo apt -y update
sudo apt -y install nginx
sudo chown -R ubuntu /var/www
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i 's/error_page 404 \/ 404.html;/error_page 404 \/custom\/404.html;/g' /etc/nginx/sites-available/default
sudo service nginx restart
