#!/usr/bin/bash
# Configures Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
custom_header="X-Served-By"
value=$(hostname)

sed -i "/a add_header $custom_header $value;" /etc/nginx/nginx.conf
nginx -s reload
