#!/usr/bin/env bash
# a Bash script that configures a server to listen to port 80

sudo apt-get uninstall nginx
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install -y nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart 
