#!/usr/bin/env bash
# Uses what we did for task #0, to make your fix short and sweet.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx stop
