#!/usr/bin/env bash
# displays the PID, along with the process name, of processes whose name contain the word bash

bash_process=$(pgrep bash)

for process in $bash_process;
do
	echo "$process bash"
done
