#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS

command="/etc/passwd"

while read -r file;
do
	IFS=:
	set ${file}
	echo "The user $1 is part of the $4 gang, lives in $6 and rides $7. $3's place is protected by the passcode $2, more info about the user here: $5"

done < "$command"
