#!/usr/bin/env bash
# configures ssh such that you can connect without typing a password

Host *
	HostName 18.209.225.36
	IdentityFile ~/.ssh/school
	PubkeyAuthentication yes
	PasswordAuthentication no
